version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - errcheck
    - errorlint
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocyclo
    - gocognit
    - gosec
    - gomoddirectives
    - ireturn
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - revive
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
