name: CI Quality Checks
on:
  pull_request:
    branches:
      - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Set up Golang 1.24
          uses: actions/setup-go@v5
          with:
           go-version: 1.24
  
        - name: Install dependencies
          run: make install
        
        - name: Run Golangci-lint
          run: make lint