name: CI Tests
on:
  pull_request:
    branches:
      - main

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Set up Golang 1.24
          uses: actions/setup-go@v5
          with:
           go-version: 1.24
        
        - name: Install Google Chrome
          uses: browser-actions/setup-chrome@v1
          id: setup-chrome
        
        - name: Install dependencies
          run: go mod tidy
        
        - name: Run tests
          run: make test
          env:
            CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
            SERVICE_REQUEST_KEY: "dummy-key::use secret in production"